name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          mkdir -p public
          echo "const API_KEY = '${{ secrets.API_KEY }}';" > public/config.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: public  # Ensure public folder is uploaded

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
