name: Test GitHub Actions

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Print a simple message to verify the workflow runs
      - name: Run a simple test
        run: echo "Hello, GitHub Actions is working!"