name: Test GitHub Actions with config.js to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Inject API Key into a config.js file
      - name: Inject API Key into config.js
        run: |
          echo "const API_KEY = '${{ secrets.API_KEY }}';" > config.js
          echo "API Key has been injected into config.js"  # This is just for logging

      # Optional: Show the content of config.js to verify
      - name: Show config.js content
        run: cat config.js

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: .  # Upload everything from the root directory
