name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Inject API Key into a config.js file (or directly into your JS files)
      - name: Inject API Key into config.js
        run: |
          echo "const API_KEY = '${{ secrets.API_KEY }}';" > config.js

      # If you have a build step (for example, bundling with Webpack or another tool)
      # you can add it here. For example:
      # - name: Build your site
      #   run: npm run build

      # Directly upload the files from the root directory (no `public` folder)
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Upload everything from the root directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy the files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1